### ISSUE TITLE
overAll

### ISSUE THREAD

**Issue by Dark32** [Dark32/RPchat2#8]
Добавить опцию включающую/выключающую слышимость канала находясь в другом канале.

В локальном не слышно публичного, в публичном - слышно локальный, глобальный слышен везде.
У публичного - overall = false

**Comment by ghost** [comment]
High Priority.
P.S. Поцелуйчики - high priority.

**Comment by Dark32** [comment]
Думал о приоритетах. Слишком сложно думать...
Нужен подробный пример.
Н-р такой:
Шёпот = 15 - локаль не слышно
Локаль = 10 - слышно шёпот, крик нет
Крик = 7 - слышно локаль и выше
Мир  = 5  - слышно крик и выше
Глобал = 0 - слышно всё, кроме паблика
Паблик = -1 - слышно всё

Это слишком путано. ОверОлл проще понять, но не так гибко.
